services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../user_management/.env

  web:
    build: ../user_management/
    restart: always
    volumes:
      - static_value:/app/staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../user_management/.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticfiles/

volumes:
  postgres_data:
  static_value: